### ISSUE TITLE
Implémentation de l'interface client

### ISSUE THREAD

**Issue by NigelSwafalgan** [PDG-Javass/IJass#21]
Il s'agit de créer l'interface client avec Svelte. Création des pages et des composants, etc.
Lié à l'User Story #12 

- [x] Accueil
- [x] Règles
- [x] Choix du type de partie
- [x] Choix de l'atout
- [x] Jeu
- [x] Score
- [x] Partie gagnante
- [x] Partie perdante

**Comment by vogelma** [comment]
Le board a été créé et les cartes sont cliquables et se déplacent sur le tapis puis disparaissent de la main.
Fini le 31 août.

**Comment by vogelma** [comment]
L'interface est prête. Il manque encore les données venant du backend.
Etat du lundi 5 septembre

**Comment by vogelma** [comment]
Le backend  et le frontend sont connectés depuis mardi 6 septembre.

**Comment by vogelma** [comment]
Une version fonctionnelle de l'application existe depuis le mercredi 7 septembre au soir.

**Comment by NigelSwafalgan** [comment]
Fini le 8 septembre, interface client complète.
