### ISSUE TITLE
issue de sécurité avec Ijass

### ISSUE THREAD

**Issue by NicolasWichoud** [PDG-Javass/IJass#28]
Bonjour à tous et toutes, @HUART1848 @magskwa @vogelma @NunezTania @NicolasWichoud 
Nous avons remarqué que vous avez un léger problème de sécurité dans votre projet

- Un gentil petit pirate

**Comment by vogelma** [comment]
Wichoud change ton mot de passe et ajoute la double authentification

**Comment by vogelma** [comment]
Le problème est réglé.
